import { DRAWING_IMAGE_ALLOW_IMAGE_LIST, ImageIoService } from '@univerjs/drawing'
import { ImageUploadStatusType, type IImageIoServiceParam } from '@univerjs/core'
import type { Nullable } from '@univerjs/core'
import { uploadImage } from '../attachments/api.ts'
import { enableSheetSvgImages } from './sheetImageTypes.ts'

/**
 * Univer's OSS image service stores selected files as base64 in the collaborative sheet state.
 * Raster images are inert there, but SVG is active XML and must cross the backend sanitizer first.
 * The signed URL below is generated by our attachment service after sanitation; only those trusted
 * bytes are converted back to base64 for Univer's existing rendering/persistence path.
 */
export class SanitizedSheetImageIoService extends ImageIoService {
  constructor(private readonly docId: string) {
    super()
    // Keep this service valid in isolation as well as through CollabSheet's picker setup.
    enableSheetSvgImages(DRAWING_IMAGE_ALLOW_IMAGE_LIST)
  }

  override async saveImage(imageFile: File): Promise<Nullable<IImageIoServiceParam>> {
    if (!(await isSvgFile(imageFile))) return super.saveImage(imageFile)

    try {
      const svgFile = new File([imageFile], ensureSvgName(imageFile.name), { type: 'image/svg+xml' })
      const uploaded = await uploadImage(this.docId, svgFile)
      if (!uploaded.src) throw new Error('missing sanitized SVG URL')

      // This is not an imported/untrusted document URL: the backend just issued it for the
      // sanitized object. Never forward browser credentials to object storage.
      const response = await fetch(uploaded.src, { credentials: 'omit' })
      if (!response.ok) throw new Error(`sanitized SVG download failed (${response.status})`)
      const bytes = await response.arrayBuffer()
      if (bytes.byteLength === 0) throw new Error('empty sanitized SVG')

      return super.saveImage(new File([bytes], svgFile.name, { type: 'image/svg+xml' }))
    } catch {
      // Preserve Univer's existing error contract so its picker shows the normal invalid-image UI.
      throw new Error(ImageUploadStatusType.ERROR_IMAGE)
    }
  }
}

async function isSvgFile(file: File): Promise<boolean> {
  const declared = file.type.trim().toLowerCase()
  if (declared === 'image/svg+xml' || declared === 'image/svg') return true
  if (!declared && /\.svg$/i.test(file.name)) return true

  // MIME metadata is caller-controlled. Content sniffing prevents a real SVG mislabeled as PNG
  // from entering collaborative state without sanitation. False positives only take the stricter
  // backend path, where non-SVG roots fail closed.
  try {
    return /<svg(?:\s|>)/i.test(await file.text())
  } catch {
    return false
  }
}

function ensureSvgName(name: string): string {
  const safe = name.trim() || 'image.svg'
  return /\.svg$/i.test(safe) ? safe : `${safe}.svg`
}
